import Footer from "@/components/functional/footer";
import Header from "@/components/functional/header";
import "@/styles/globals.css";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Shopdesk",
  description: "Generated by create next app",
};
const pathname = typeof window !== "undefined" ? window.location.pathname : "";
const hideLayoutPages = ["/login"];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        {!hideLayoutPages.includes(pathname) && <Header />}
        {children}
        {!hideLayoutPages.includes(pathname) && <Footer />}
      </body>
    </html>
  );
}
